"""Parser for mirror directory index pages (nginx/Apache autoindex).

Why this exists: a few release artefacts are only discoverable by
listing a directory. ``isos/<arch>/`` forced the issue — the ISO file
names carry a respin counter (``AlmaLinux-10.3-beta-1-…``) that cannot
be derived from ``ALMA_VERSION``, and "the ISO is not there" has to be
a failure rather than an inference from a ``CHECKSUM`` file that may
itself be missing.

Regex-based on purpose: we need nothing but the ``href`` targets, the
index is machine-generated by the mirror, and an HTML parser would be a
new runtime dependency for a job that does not need one.
"""

from __future__ import annotations

import re
from urllib.parse import unquote

# nginx's autoindex emits one ``<a href="NAME">NAME</a>`` per entry;
# Apache's adds column-sort links and an absolute breadcrumb, both of
# which ``parse_hrefs`` filters out below.
_RE_HREF = re.compile(r"<a\s[^>]*href=\"([^\"]+)\"", re.IGNORECASE)


def parse_hrefs(html: str) -> list[str]:
    """Entry names linked from a directory index page, in listing order.

    Dropped, because they are navigation rather than directory content:

    * the parent link (``../``, ``./``), any absolute path and any full
      URL — an Apache index links ``/almalinux/10.3-beta/`` as a
      breadcrumb;
    * Apache's column-sort links (``?C=N;O=D``) and fragments.

    Percent-escapes are decoded so the result can be compared against
    real file names. Duplicates collapse to their first occurrence
    (Apache links the same entry twice, once for the icon) while the
    listing order is preserved.
    """
    out: list[str] = []
    seen: set[str] = set()
    for raw in _RE_HREF.findall(html):
        if raw.startswith(("/", "?", "#")) or "://" in raw:
            continue
        name = unquote(raw)
        if name in ("", "./", "../") or name in seen:
            continue
        seen.add(name)
        out.append(name)
    return out


def files(html: str, *, suffix: str = "") -> list[str]:
    """File entries of an index page, optionally filtered by ``suffix``.

    An autoindex marks directories with a trailing ``/``; everything
    else is a file. ``suffix`` is compared case-insensitively so a
    mirror that ever publishes ``.ISO`` does not read as "no ISOs
    published at all".
    """
    out: list[str] = []
    for name in parse_hrefs(html):
        if name.endswith("/"):
            continue
        if suffix and not name.lower().endswith(suffix.lower()):
            continue
        out.append(name)
    return out
