"""Unit tests for the CHECKSUM parsers in post_check.helpers.iso.

These tests do NOT hit the network and do NOT require GPG — these are
pure parser checks: ``parse_checksum`` (name → sha256) and
``declared_sizes`` (name → expected byte count).
"""

from post_check.helpers.iso import declared_sizes, parse_checksum


def test_clearsigned_checksum_parser_extracts_pairs():
    payload = "SHA256 (AlmaLinux-10.1-x86_64-dvd.iso) = " + "a" * 64 + "\n"
    pairs = parse_checksum(payload)
    assert len(pairs) == 1
    assert pairs[0].filename == "AlmaLinux-10.1-x86_64-dvd.iso"
    assert pairs[0].sha256 == "a" * 64


def test_clearsigned_checksum_parser_extracts_multiple_pairs():
    payload = (
        f"SHA256 (AlmaLinux-10.1-x86_64-dvd.iso) = {'a' * 64}\n"
        f"SHA256 (AlmaLinux-10.1-x86_64-boot.iso) = {'b' * 64}\n"
        f"SHA256 (AlmaLinux-10.1-x86_64-minimal.iso) = {'c' * 64}\n"
    )
    pairs = parse_checksum(payload)
    assert len(pairs) == 3
    names = [p.filename for p in pairs]
    assert "AlmaLinux-10.1-x86_64-dvd.iso" in names
    assert "AlmaLinux-10.1-x86_64-boot.iso" in names
    assert "AlmaLinux-10.1-x86_64-minimal.iso" in names


def test_clearsigned_checksum_parser_returns_empty_for_garbage():
    """Boundary check: empty input and random text must yield an empty
    list, not an exception. ``test_iso_checksums.py`` then asserts
    ``assert pairs, "has the CHECKSUM format changed?"`` — that
    operator-facing message only ever fires if the parser is well-
    behaved on garbage input.
    """
    assert parse_checksum("") == []
    assert parse_checksum("not a checksum file at all\n") == []


def test_clearsigned_checksum_parser_rejects_short_hash():
    """A hash shorter than 64 hex characters should not be recognized."""
    payload = f"SHA256 (foo.iso) = {'a' * 32}\n"
    assert parse_checksum(payload) == []


# ------------------------------------------------------------ declared sizes
# The ``# <name>: <N> bytes`` comment lines are what lets
# ``test_iso_presence`` tell a complete ISO upload from a truncated one
# without downloading 10 GiB.


def test_declared_sizes_extracts_the_comment_lines():
    payload = (
        "# AlmaLinux-10.3-beta-1-aarch64-boot.iso: 1030670336 bytes\n"
        f"SHA256 (AlmaLinux-10.3-beta-1-aarch64-boot.iso) = {'a' * 64}\n"
        "# AlmaLinux-10-latest-beta-aarch64-boot.iso: 1030670336 bytes\n"
        f"SHA256 (AlmaLinux-10-latest-beta-aarch64-boot.iso) = {'a' * 64}\n"
    )
    assert declared_sizes(payload) == {
        "AlmaLinux-10.3-beta-1-aarch64-boot.iso": 1030670336,
        "AlmaLinux-10-latest-beta-aarch64-boot.iso": 1030670336,
    }


def test_declared_sizes_is_empty_when_no_sizes_are_published():
    """Size comments are not part of ``sha256sum --tag`` output, so a
    CHECKSUM without them is valid. The consumer degrades to a
    plausibility floor rather than failing — pin the empty result that
    behaviour depends on.
    """
    payload = f"SHA256 (AlmaLinux-10.2-x86_64-dvd.iso) = {'a' * 64}\n"
    assert declared_sizes(payload) == {}
    assert declared_sizes("") == {}


def test_declared_sizes_ignores_other_comment_lines():
    """Only ``<name>: <N> bytes`` counts; a free-form comment must not
    be mistaken for a size declaration."""
    payload = (
        "# Generated by the AlmaLinux release tooling\n"
        "# AlmaLinux-10.2-x86_64-dvd.iso: not yet computed\n"
        "# AlmaLinux-10.2-x86_64-boot.iso: 1065881600 bytes\n"
    )
    assert declared_sizes(payload) == {
        "AlmaLinux-10.2-x86_64-boot.iso": 1065881600
    }
